// Generated by CoffeeScript 1.4.0
(function() {
  var getXHR, injectJS, require;

  require = function(path) {
    if (!(path in require.required)) {
      window.exports = {};
      window.module = window;
      injectJS("" + path + ".js");
      require.required[path] = window.exports;
      delete window.exports;
      delete window.module;
    }
    return require.required[path];
  };

  require.required = {};

  getXHR = function() {
    var ret;
    if (window.XMLHttpRequest) {
      ret = new XMLHttpRequest;
    } else {
      try {
        ret = new ActiveXObject('Msxml2.XMLHTTP');
      } catch (e) {
        ret = new ActiveXObject('Microsoft.XMLHTTP');
      }
    }
    return ret;
  };

  injectJS = function(url) {
    var head, script, xhr;
    xhr = getXHR();
    xhr.open('GET', url, false);
    xhr.send('');
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.text = xhr.responseText;
    head = document.getElementsByTagName('head')[0];
    return head.appendChild(script);
  };

  window.require = require;

}).call(this);

window.exports = {};
window.module = window;
// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    version: 'v0.0.1',
    echo: function(msg) {
      return msg;
    }
  };

}).call(this);

require.required["lib/lib1"] = window.exports;
window.exports = {};
window.module = window;
// Generated by CoffeeScript 1.4.0
(function() {
  var echo;

  echo = require('lib/lib1').echo;

  exports.echo2 = function(msg) {
    return "" + (echo(msg)) + " " + (echo(msg));
  };

  exports.version = 'v0.0.3';

}).call(this);

require.required["lib/lib2"] = window.exports;
window.exports = {};
window.module = window;
// Generated by CoffeeScript 1.4.0
(function() {
  var should;

  should = chai.should();

  mocha.setup('bdd');

  describe('require', function() {
    it('should load script synchrously', function() {
      var lib1;
      lib1 = require('lib/lib1');
      (typeof lib1.echo).should.equal('function');
      return lib1.echo('echo').should.equal('echo');
    });
    return it('should load script in loaded script', function() {
      var lib2;
      lib2 = require('lib/lib2');
      (typeof lib2.echo2).should.equal('function');
      return lib2.echo2('echo').should.equal('echo echo');
    });
  });

}).call(this);

require.required["test"] = window.exports;
