window.require = function(key){
	return require.required[key];
}
window.require.required = {};
(function(require){
	exports = {};
	module = {exports:exports};
	(function(exports,module,require){
		// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    version: 'v0.0.1',
    echo: function(msg) {
      return msg;
    }
  };

}).call(this);

	})(exports,module,require);
	require.required["lib/lib1"] = exports;
})(window.require)
(function(require){
	exports = {};
	module = {exports:exports};
	(function(exports,module,require){
		// Generated by CoffeeScript 1.4.0
(function() {
  var echo;

  echo = require('./lib1').echo;

  exports.echo2 = function(msg) {
    return "" + (echo(msg)) + " " + (echo(msg));
  };

  exports.version = 'v0.0.3';

}).call(this);

	})(exports,module,require);
	require.required["lib/lib2"] = exports;
})(window.require)
(function(require){
	exports = {};
	module = {exports:exports};
	(function(exports,module,require){
		// Generated by CoffeeScript 1.4.0
(function() {
  var should;

  should = chai.should();

  mocha.setup('bdd');

  describe('require', function() {
    it('should load script synchrously', function() {
      var lib1;
      lib1 = require('./lib/lib1');
      (typeof lib1.echo).should.equal('function');
      return lib1.echo('echo').should.equal('echo');
    });
    return it('should load script in loaded script', function() {
      var lib2;
      lib2 = require('./lib/lib2');
      (typeof lib2.echo2).should.equal('function');
      return lib2.echo2('echo').should.equal('echo echo');
    });
  });

}).call(this);

	})(exports,module,require);
	require.required["test"] = exports;
})(window.require)