// Generated by CoffeeScript 1.4.0
(function() {
  var container, getXHR, injectJS, require;

  container = {};

  require = function(path) {
    if (!(path in container)) {
      window.exports = {};
      window.module = window;
      injectJS("" + path + ".js");
      container[path] = window.exports;
      delete window.exports;
      delete window.module;
    }
    return container[path];
  };

  getXHR = function() {
    var ret;
    if (window.XMLHttpRequest) {
      ret = new XMLHttpRequest;
    } else {
      try {
        ret = new ActiveXObject('Msxml2.XMLHTTP');
      } catch (e) {
        ret = new ActiveXObject('Microsoft.XMLHTTP');
      }
    }
    return ret;
  };

  injectJS = function(url) {
    var head, script, xhr;
    xhr = getXHR();
    xhr.open('GET', url, false);
    xhr.send('');
    script = document.createElement('script');
    script.type = 'text/javascript';
    script.text = xhr.responseText;
    head = document.getElementsByTagName('head')[0];
    return head.appendChild(script);
  };

  window.require = require;

}).call(this);
