// Generated by CoffeeScript 1.6.2
(function() {
  var echo;

  echo = require('./lib1').echo;

  exports.echo2 = function(msg) {
    return "" + (echo(msg)) + " " + (echo(msg));
  };

  exports.version = 'v0.0.3';

}).call(this);
